substitutions:
  fan_id: new_fan
  fan_switch_id: blow_switch
  
  source_sensor_id: dht_hum
  
  blow_timeout: 30min

  #pin_buzzer: GPIO15
  pin_btn: GPIO14
  pin_relay1: GPIO13
  pin_relay2: GPIO12

  fan_speed_1: '50'
  fan_speed_2: '70'
  fan_speed_3: '90'


sensor:
  - platform: dht
    # Пин data датчика
    pin: D1
    model: AM2302
    temperature:
      name: "Temperature"
      id: dht_temp
    humidity:
      name: "Humidity"
      id: $source_sensor_id
    update_interval: 1min
    on_value:
      then:
        - script.execute: fan_automation
    
