substitutions:
  fan_id: new_fan
  fan_switch_id: blow_switch
  
  source_sensor_id: dht_hum

  pin_btn: D5
  pin_relay1: D6
  pin_relay2: D7

  fan_speed_1_above: '50'
  fan_speed_2_above: '70'
  fan_speed_3_above: '90'


sensor:
  - platform: dht
    # Пин data датчика
    pin: D1
    model: AM2302
    temperature:
      name: "Temperature"
      id: dht_temp
    humidity:
      name: "Humidity"
      id: $source_sensor_id
    update_interval: 1min
    
