substitutions:
  fan_id: new_fan
  fan_switch_id: blow_switch
  
  source_sensor_id: hass_humidity
  
  blow_timeout: 30min
  
  #pin_buzzer: GPIO15
  pin_btn: GPIO14
  pin_relay1: GPIO13
  pin_relay2: GPIO12
  
  bound_1: '50'
  bound_2: '70'
  bound_3: '90'

sensor:
  - platform: homeassistant
    name: "Humidity Sensor"
    # `sensor.humidity_2` замените на ваш датчик из Home Assistant
    entity_id: sensor.humidity_2
    id: $source_sensor_id
    on_value:
      then:
        - script.execute: fan_automation
