substitutions:
  fan_id: new_fan
  fan_switch_id: blow_switch
  
  source_sensor_id: mhz19_co2
  
  blow_timeout: 30min
  
  pin_btn: D5
  pin_relay1: D6
  pin_relay2: D7
  
  fan_speed_1: '600'
  fan_speed_2: '1200'
  fan_speed_3: '1800'
  
  
uart:
  rx_pin: RX
  tx_pin: TX
  baud_rate: 9600
  
  
sensor:
  - platform: mhz19
    co2:
      name: "CO2 Value"
      id: $source_sensor_id
    temperature:
      name: "Temperature"
      id: mhz19_temp
    update_interval: 1min
    automatic_baseline_calibration: false
